# Generated by Django 3.0.4 on 2020-04-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Task',
        ),
    ]
